language: c++
os:
 - linux
 - osx
 
osx_image: xcode7.3

sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9

before_install:
  - ifmac () { if [[ $TRAVIS_OS_NAME == osx ]]; then eval $@; fi; }
  - iflin () { if [[ $TRAVIS_OS_NAME == linux ]]; then eval $@; fi; }
  - iflin sudo apt-get update
  - ifmac brew update
  - iflin mkdir cmake && travis_retry wget --quiet --no-check-certificate -O - https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | tar --strip-components=1 -xz -C cmake
  - ifmac mkdir cmake && travis_retry wget --quiet --no-check-certificate -O - https://cmake.org/files/v3.5/cmake-3.5.2-Darwin-x86_64.tar.gz | tar --strip-components=1 -xz -C cmake
  - export PATH=$PWD/cmake/bin:${PATH}
  - cmake/bin/cmake --version
  - cmake --version
  - $COMPILER --version

# command to install dependencies
install: true
  
# command to make the build
script:
  - mkdir build && cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
  - make


