language: c++

before_install:
  - sudo apt-get update
  - sudo apt-get install cmake
  - sudo apt-get install gcc
  
# command to install dependencies
install: true
  
# command to make the build
script:
  - mkdir build
  - cd build
  - cmake ..


